### ISSUE TITLE
/tpd command is not loaded

### ISSUE THREAD

**Issue by PATAPOsha** [GeheimagentNr1/DimensionTeleport#2]
**Versions**
Minecraft Version: 1.20.1
Minecraft Forge Version: 47.1.0
Mod Version: 2.0.1

**Describe the bug**
`/tpd` command is not shown in autocomplete and not recognized.

![image](https://github.com/GeheimagentNr1/DimensionTeleport/assets/14761219/e9efdbb2-3279-410c-ab1c-ae1ccfc8fa6f)

![image](https://github.com/GeheimagentNr1/DimensionTeleport/assets/14761219/92c5df20-fb54-4ddb-bf8d-7fa8c83b9d70)

Complete list of mods:
![image](https://github.com/GeheimagentNr1/DimensionTeleport/assets/14761219/c15c1e45-1445-4c5b-81fc-25b1e01f9c05)

Previously, I had [QuickTeleports](https://github.com/itsmeow/QuickTeleports) installed. It worked fine, but it is not updated to 1.20.1.

**Comment by PATAPOsha** [comment]
Turns out, you have to "Enable cheats" when opening a server to LAN to make mod work.

**Comment by PATAPOsha** [comment]
Is there option to use it like request/accept tp between players only?

**Comment by GeheimagentNr1** [comment]
No, it is just a command for mods like the default /tp command.
